// Generated by mithril wasp generate from Mithril Core v0 model "Acme".  DO NOT EDIT.
// The minimal static client shell Wasp requires; the generated Action is
// exercised over Wasp's real HTTP and authentication path, not from here.
export function MainPage() {
  return (
    <main>
      <h1>{"Mithril Core v0 model \"Acme\""}</h1>
      <p>{"Wasp Confinement Profile v0 demonstrator: one authenticated Wasp Action, mithrilCaseAction (POST /operations/mithril-case-action), lowered from the supported NoSelfPrivilegeEscalation case action shape of \"Membership.changeRole\"."}</p>
    </main>
  );
}
