// Generated by mithril wasp generate from Mithril Core v0 model "Acme".  DO NOT EDIT.
import { defineConfig } from "vite";
import { wasp } from "wasp/client/vite";

export default defineConfig({
  plugins: [wasp()],
});
