// Generated by mithril wasp generate from Mithril Core v0 model "Acme".  DO NOT EDIT.
//
// Wasp Confinement Profile v1: this specification is a managed input of the
// closed generated profile; mithril wasp check rejects any byte that differs
// from the regenerated bundle.  It declares exactly one route and page (the
// minimal client shell) and exactly two authenticated Actions, both exported by
// the one generated operation file, in the authored case order:
//   mithrilCaseAction, lowered from the change-other (rule-1) case action
//   "Membership.changeRole" (case 0), and
//   mithrilSelfUpdateAction, lowered from the bounded self-update (rule-2) case action
//   "Membership.changeOwnRole" (case 1).
// Lowering attests support of the shape only; the generating command's report,
// not these bytes, states whether the document passed the proof gate.
// No query, API, CRUD, job, seed, server setup, or middleware path exists.
import { action, app, page, route } from "@wasp.sh/spec";
import { MainPage } from "./src/MainPage" with { type: "ref" };
import { mithrilCaseAction, mithrilSelfUpdateAction } from "./src/mithrilCaseAction" with { type: "ref" };

export default app({
  name: "mithrilWaspApp",
  wasp: { version: "0.25.0" },
  title: "Acme",
  auth: {
    userEntity: "MithrilSubject",
    methods: { usernameAndPassword: {} },
    onAuthFailedRedirectTo: "/",
  },
  spec: [
    route("RootRoute", "/", page(MainPage)),
    action(mithrilCaseAction, { entities: ["MithrilAuthority"], auth: true }),
    action(mithrilSelfUpdateAction, { entities: ["MithrilAuthority"], auth: true }),
  ],
});
