// Generated by mithril wasp generate from Mithril Core v0 model "Acme".  DO NOT EDIT.
// The minimal static client shell Wasp requires; the generated Actions are
// exercised over Wasp's real HTTP and authentication path, not from here.
export function MainPage() {
  return (
    <main>
      <h1>{"Mithril Core v0 model \"Acme\""}</h1>
      <p>{"Wasp Confinement Profile v1 demonstrator: two authenticated Wasp Actions in the authored case order, mithrilCaseAction (POST /operations/mithril-case-action), lowered from the change-other NoSelfPrivilegeEscalation case action \"Membership.changeRole\", and mithrilSelfUpdateAction (POST /operations/mithril-self-update-action), lowered from the bounded self-update NoSelfPrivilegeEscalation case action \"Membership.changeOwnRole\"."}</p>
    </main>
  );
}
