// Generated by mithril wasp generate from Mithril Core v0 model "Acme".  DO NOT EDIT.
//
// Wasp Confinement Profile v1: the two generated security-sensitive operations of
// this application, in the authored case order — the NoSelfPrivilegeEscalation
// case action "Membership.changeRole" (action 4, case 0), lowered as the Wasp Action
// mithrilCaseAction (POST /operations/mithril-case-action), and the case action
// "Membership.changeOwnRole" (action 5, case 1), lowered as the Wasp Action
// mithrilSelfUpdateAction (POST /operations/mithril-self-update-action).  This is the
// only file of the profile permitted to import prisma from "wasp/server"; mithril
// wasp check rejects any byte that differs from the regenerated bundle.  Every
// identifier below is a fixed target name of the profile; the authored Core
// names appear only in comments and string metadata.
// Lowering attests support of the shape only; the generating command's report,
// not these bytes, states whether the document passed the proof gate.
//
// Consumed normalized evidence:
//   model: "Acme"
//   guarantee: NoSelfPrivilegeEscalation
//   authority relation: "Membership" (relation 0)
//   authority subject endpoint: "user" (endpoint 0 of relation 0), entity "User" (entity 0)
//   authority scope endpoint: "organization" (endpoint 1 of relation 0), entity "Organization" (entity 1)
//   authority absence level: Bottom
//   authority payload order: enum "MembershipRole" (enum 0)
//   declared enum members: "Member" (value 0 of enum 0), "Admin" (value 1 of enum 0)
//   materialized authority ranking: rank 0 = "Member" (value 0 of enum 0), rank 1 = "Admin" (value 1 of enum 0)
//   materialized bottom: rank 0 = "Member" (value 0 of enum 0)
//   privilege floor: rank 1 = "Admin" (value 1 of enum 0)
//   absent rank: -1
//   selected cases: 2
//   case 0: rule 1 (change-other)
//   case action: "Membership.changeRole" (action 4)
//   case scope binding: endpoint "organization" (endpoint 1) = Argument "organization" (parameter 1)
//   principal mode: AuthenticatedOnly
//   parameter 0: "target" : EntityRef "User"
//   parameter 1: "organization" : EntityRef "Organization"
//   parameter 2: "newRole" : Enum "MembershipRole"
//   allow policy: And(LessOrEqual[order optional "MembershipRole", absence as bottom](Some(Enum["MembershipRole"."Admin"]), Lookup["Membership"]("user" = Actor, "organization" = Argument["organization"])), And(Not(Equal(Actor, Argument["target"])), IsSome(Lookup["Membership"]("user" = Argument["target"], "organization" = Argument["organization"]))))
//   effect: SetRelation["Membership"](endpoint "user" (endpoint 0) = Argument "target" (parameter 0), endpoint "organization" (endpoint 1) = Argument "organization" (parameter 1)) payload Argument["newRole"]
//   result: Done
//   case 1: rule 2 (bounded-self-update)
//   case action: "Membership.changeOwnRole" (action 5)
//   case scope binding: endpoint "organization" (endpoint 1) = Argument "organization" (parameter 0)
//   principal mode: AuthenticatedOnly
//   parameter 0: "organization" : EntityRef "Organization"
//   parameter 1: "newRole" : Enum "MembershipRole"
//   allow policy: LessOrEqual[order optional "MembershipRole", absence as bottom](Some(Argument["newRole"]), Lookup["Membership"]("user" = Actor, "organization" = Argument["organization"]))
//   effect: SetRelation["Membership"](endpoint "user" (endpoint 0) = Actor, endpoint "organization" (endpoint 1) = Argument "organization" (parameter 0)) payload Argument["newRole"]
//   result: Done
//
// Target-name mapping: entity references are the Int identities of the Prisma
// models MithrilSubject ("User") and MithrilScope ("Organization"); the
// authority relation "Membership" is the Prisma model MithrilAuthority
// identified by (subjectId, scopeId):
//   subjectId for the endpoint "user",
//   scopeId for the endpoint "organization",
// with the payload column payload of the enum MithrilPayload ("MembershipRole").  The arguments of mithrilCaseAction
//   subject carries the parameter "target",
//   scope carries the parameter "organization",
//   payload carries the parameter "newRole";
// the arguments of mithrilSelfUpdateAction
//   scope carries the parameter "organization",
//   payload carries the parameter "newRole",
// and its subject is the authenticated principal itself (no subject argument exists);
// absence of a tuple takes the absent rank below every member.
import { HttpError, prisma } from "wasp/server";
import type { MithrilCaseAction, MithrilSelfUpdateAction } from "wasp/server/operations";

// The authority payload enum MithrilPayload ("MembershipRole"): the values in
// declaration order,
//   Value0 = "Member", Value1 = "Admin".
type Payload = "Value0" | "Value1";
const payloadMembers: readonly string[] = ["Value0", "Value1"];

// The materialized ranking (rank 0 is the bottom ranked value):
//   rank 0 = Value0 ("Member"), rank 1 = Value1 ("Admin");
// the privilege floor is the rank of Value1 ("Admin"), and an absent authority
// tuple takes the absent rank below every member (absence level Bottom).
const payloadRank: Readonly<Record<Payload, number>> = { "Value0": 0, "Value1": 1 };
const floorRank = 1;
const absentRank = -1;

// Bounded deterministic retry of Serializable write conflicts (Prisma P2034).
const serializationAttempts = 3;

// The action's arguments: subject carries "target" : EntityRef "User",
// scope carries "organization" : EntityRef "Organization", and payload carries
// "newRole" : Enum "MembershipRole".
type Args = { subject: number; scope: number; payload: Payload };

function isEntityReference(value: unknown): value is number {
  return typeof value === "number" && Number.isSafeInteger(value) && value >= 1;
}

function isPayload(value: unknown): value is Payload {
  return typeof value === "string" && payloadMembers.includes(value);
}

function parseArgs(input: unknown): Args | null {
  if (typeof input !== "object" || input === null) {
    return null;
  }
  const record = input as Record<string, unknown>;
  const subjectArgument = record["subject"];
  const scopeArgument = record["scope"];
  const payloadArgument = record["payload"];
  if (!isEntityReference(subjectArgument) || !isEntityReference(scopeArgument) || !isPayload(payloadArgument)) {
    return null;
  }
  return { subject: subjectArgument, scope: scopeArgument, payload: payloadArgument };
}

function isSerializationConflict(error: unknown): boolean {
  return typeof error === "object" && error !== null && (error as { code?: unknown }).code === "P2034";
}

export const mithrilCaseAction: MithrilCaseAction<Args, void> = async (input, context) => {
  // Principal: Wasp authentication is required, and context.user.id is the only
  // identity the Action uses (the subject entity MithrilSubject, authored "User").
  if (!context.user) {
    throw new HttpError(401, "authentication required");
  }
  const actor: number = context.user.id;
  const args = parseArgs(input);
  if (args === null) {
    throw new HttpError(400, "invalid arguments");
  }
  for (let attempt = 1; ; attempt += 1) {
    try {
      await prisma.$transaction(
        async (tx) => {
          // Lookup["Membership"]("user" = Actor, "organization" = Argument["organization"]):
          // all mutable authorization state is read inside this Serializable transaction.
          const actorTuple = await tx.mithrilAuthority.findUnique({
            where: { subjectId_scopeId: { subjectId: actor, scopeId: args.scope } },
          });
          // Lookup["Membership"]("user" = Argument["target"], "organization" = Argument["organization"]).
          const targetTuple = await tx.mithrilAuthority.findUnique({
            where: { subjectId_scopeId: { subjectId: args.subject, scopeId: args.scope } },
          });
          const actorRank = actorTuple === null ? absentRank : payloadRank[actorTuple.payload];
          // And(LessOrEqual(Some("Admin"), actor authority), And(Not(Equal(Actor, "target")), IsSome(target authority))).
          const allowed = floorRank <= actorRank && (!(actor === args.subject) && targetTuple !== null);
          if (!allowed) {
            throw new HttpError(403, "forbidden");
          }
          // SetRelation["Membership"]("user" = Argument["target"], "organization" = Argument["organization"]) payload Argument["newRole"].
          await tx.mithrilAuthority.update({
            where: { subjectId_scopeId: { subjectId: args.subject, scopeId: args.scope } },
            data: { payload: args.payload },
          });
        },
        { isolationLevel: "Serializable" },
      );
      return;
    } catch (error) {
      if (error instanceof HttpError) {
        throw error;
      }
      if (isSerializationConflict(error)) {
        if (attempt < serializationAttempts) {
          continue;
        }
        throw new HttpError(409, "conflict");
      }
      throw new HttpError(500, "internal error");
    }
  }
};

// The self-update action's arguments: scope carries "organization" : EntityRef "Organization" and
// payload carries "newRole" : Enum "MembershipRole"; the subject of the
// write is the authenticated principal itself, so no subject argument exists.
type SelfUpdateArgs = { scope: number; payload: Payload };

function parseSelfUpdateArgs(input: unknown): SelfUpdateArgs | null {
  if (typeof input !== "object" || input === null) {
    return null;
  }
  const record = input as Record<string, unknown>;
  const scopeArgument = record["scope"];
  const payloadArgument = record["payload"];
  if (!isEntityReference(scopeArgument) || !isPayload(payloadArgument)) {
    return null;
  }
  return { scope: scopeArgument, payload: payloadArgument };
}

export const mithrilSelfUpdateAction: MithrilSelfUpdateAction<SelfUpdateArgs, void> = async (input, context) => {
  // Principal: Wasp authentication is required, and context.user.id is the only
  // identity the Action uses — it is also the subject of the write (the subject
  // entity MithrilSubject, authored "User").
  if (!context.user) {
    throw new HttpError(401, "authentication required");
  }
  const actor: number = context.user.id;
  const args = parseSelfUpdateArgs(input);
  if (args === null) {
    throw new HttpError(400, "invalid arguments");
  }
  for (let attempt = 1; ; attempt += 1) {
    try {
      await prisma.$transaction(
        async (tx) => {
          // Lookup["Membership"]("user" = Actor, "organization" = Argument["organization"]):
          // the actor's own authority tuple, read inside this Serializable transaction.
          const actorTuple = await tx.mithrilAuthority.findUnique({
            where: { subjectId_scopeId: { subjectId: actor, scopeId: args.scope } },
          });
          const actorRank = actorTuple === null ? absentRank : payloadRank[actorTuple.payload];
          // LessOrEqual(Some(Argument["newRole"]), actor authority): the requested
          // payload is bounded by the actor's own pre-state authority; an absent tuple
          // takes the absent rank below every member, so no separate membership
          // condition exists.
          const allowed = payloadRank[args.payload] <= actorRank;
          if (!allowed) {
            throw new HttpError(403, "forbidden");
          }
          // SetRelation["Membership"]("user" = Actor, "organization" = Argument["organization"]) payload Argument["newRole"]: exactly the tuple read above.
          await tx.mithrilAuthority.update({
            where: { subjectId_scopeId: { subjectId: actor, scopeId: args.scope } },
            data: { payload: args.payload },
          });
        },
        { isolationLevel: "Serializable" },
      );
      return;
    } catch (error) {
      if (error instanceof HttpError) {
        throw error;
      }
      if (isSerializationConflict(error)) {
        if (attempt < serializationAttempts) {
          continue;
        }
        throw new HttpError(409, "conflict");
      }
      throw new HttpError(500, "internal error");
    }
  }
};
